### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by makew0rld** [JorelAli/mdBook-pagetoc#1]
It's not clear how this project can be used without a LICENSE file. I recommend the MIT license.

**Comment by JorelAli** [comment]
I've added a suitable license in [this commit](cb50a3c710a2b79f592e0494fd89349372d4ee37).

**Comment by makew0rld** [comment]
That's not a very robust LICENSE, but it's better than not having one, so thanks. I think you made an error though? It says:
```
Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>
```

**Comment by JorelAli** [comment]
Fixed.

**Comment by makew0rld** [comment]
Thanks! I hate to keep bothering you, but the year should be 2020, not 2004.

**Comment by JorelAli** [comment]
It's fine - you've raised some good points! I should probably review my other repositories at some point now that you've brought this to my attention. Thanks :smiley:
