### ISSUE TITLE
Next page icon can overlap table of contents

### ISSUE THREAD

**Issue by nathaneastwood** [JorelAli/mdBook-pagetoc#10]
I was playing around with the width and noticed that at some point, the next page icon can overlap on top of the table of contents. Might it be an idea that the width selection takes this into account?

<img width="1502" alt="Screenshot 2022-09-08 at 13 17 27" src="https://user-images.githubusercontent.com/9799530/189119671-12c874d3-389c-47b7-a4c7-4b1a3f971236.png">

**Comment by JorelAli** [comment]
Fixed by #14.
