### ISSUE TITLE
Cargo.lock missing from repository

### ISSUE THREAD

**Issue by matthiasbeyer** [JorelAli/mdBook-pagetoc#12]
Please add the `Cargo.lock` file. Found that it is missing when trying to package this for nixpkgs.

**Comment by figsoda** [comment]
I'm not sure if this is a rust project, there is no `Cargo.toml` either

**Comment by JorelAli** [comment]
This is not a Rust project. It's simply a project with a bit of JavaScript and CSS and are just additional files to use when creating your own mdBook.

**Comment by matthiasbeyer** [comment]
Hah! Sorry, I totally missed that because all other `mdbook-*` tools are written in Rust.
