### ISSUE TITLE
Example often highlights the wrong heading.

### ISSUE THREAD

**Issue by pragmatrix** [JorelAli/mdBook-pagetoc#7]
For some sections the wrong sidebar entries are highlighted. For example https://jorel.dev/mdBook-pagetoc/chapter_2.html#apricot stays on `orange`.

Tested with Chrome and Firefox latest.

**Comment by JorelAli** [comment]
My implementation of the in-page table-of-contents selects the heading which it believes "is visible". If you say, scrolled to the end and clicked on a heading, the respective heading in the table of contents won't update as it doesn't look at currently selected headings in mdbook itself.
