### ISSUE TITLE
Doesn't work on Safari

### ISSUE THREAD

**Issue by nathaneastwood** [JorelAli/mdBook-pagetoc#9]
Hi, I really like the look of this. I tried it out on my Mac but it doesn't show the ToC in Safari.

**Comment by JorelAli** [comment]
Unfortunately, I don't own a Mac so I can't test this out on my machine.

Currently, the ToC only displays if the screen is wide enough (1440px). Can you ensure that your screen is wide enough to display the ToC?

If the ToC still doesn't display, does the console display any errors/warnings that I could use to look into the issue?

**Comment by nathaneastwood** [comment]
Ah, interesting. So it was showing in Chrome which was why I assumed it wasn't working for Safari. I just plugged my laptop into my external monitor and it is indeed now showing in Safari, thanks!
